# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommWithReplica.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x43ommWithReplica.proto\"#\n\x07\x41\x64\x64ress\x12\n\n\x02IP\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\")\n\x17SendDetailsOfPRResponse\x12\x0e\n\x06Status\x18\x01 \x01(\t2J\n\x0f\x43ommWithReplica\x12\x37\n\x0fSendDetailsOfPR\x12\x08.Address\x1a\x18.SendDetailsOfPRResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CommWithReplica_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDRESS._serialized_start=25
  _ADDRESS._serialized_end=60
  _SENDDETAILSOFPRRESPONSE._serialized_start=62
  _SENDDETAILSOFPRRESPONSE._serialized_end=103
  _COMMWITHREPLICA._serialized_start=105
  _COMMWITHREPLICA._serialized_end=179
# @@protoc_insertion_point(module_scope)
