# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import CommWithReplica_pb2 as CommWithReplica__pb2


class CommWithServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDetailsToPR = channel.unary_unary(
                '/CommWithServer/SendDetailsToPR',
                request_serializer=CommWithReplica__pb2.Address.SerializeToString,
                response_deserializer=CommWithReplica__pb2.SendDetailsToPRResponse.FromString,
                )


class CommWithServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendDetailsToPR(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommWithServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDetailsToPR': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDetailsToPR,
                    request_deserializer=CommWithReplica__pb2.Address.FromString,
                    response_serializer=CommWithReplica__pb2.SendDetailsToPRResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CommWithServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommWithServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendDetailsToPR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CommWithServer/SendDetailsToPR',
            CommWithReplica__pb2.Address.SerializeToString,
            CommWithReplica__pb2.SendDetailsToPRResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
