# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommWithReplica.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x43ommWithReplica.proto\x1a\x1fgoogle/protobuf/timestamp.proto\";\n\x0cWriteRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x1b\n\x0bReadRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\x1d\n\rDeleteRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"Z\n\rWriteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12+\n\x07version\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"j\n\x0cReadResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12+\n\x07version\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1e\n\x0cStatusRepReq\x12\x0e\n\x06status\x18\x01 \x01(\t\"1\n\x07\x41\x64\x64ress\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x32\x8d\x01\n\x0f\x43ommWithReplica\x12(\n\x05Write\x12\r.WriteRequest\x1a\x0e.WriteResponse\"\x00\x12%\n\x04Read\x12\x0c.ReadRequest\x1a\r.ReadResponse\"\x00\x12)\n\x06\x44\x65lete\x12\x0e.DeleteRequest\x1a\r.StatusRepReq\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CommWithReplica_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WRITEREQUEST._serialized_start=58
  _WRITEREQUEST._serialized_end=117
  _READREQUEST._serialized_start=119
  _READREQUEST._serialized_end=146
  _DELETEREQUEST._serialized_start=148
  _DELETEREQUEST._serialized_end=177
  _WRITERESPONSE._serialized_start=179
  _WRITERESPONSE._serialized_end=269
  _READRESPONSE._serialized_start=271
  _READRESPONSE._serialized_end=377
  _STATUSREPREQ._serialized_start=379
  _STATUSREPREQ._serialized_end=409
  _ADDRESS._serialized_start=411
  _ADDRESS._serialized_end=460
  _COMMWITHREPLICA._serialized_start=463
  _COMMWITHREPLICA._serialized_end=604
# @@protoc_insertion_point(module_scope)
