# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommWithRegistryServer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x43ommWithRegistryServer.proto\"#\n\x07\x41\x64\x64ress\x12\n\n\x02IP\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"Q\n\x17RegisterReplicaResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12&\n\x14primaryServerAddress\x18\x02 \x01(\x0b\x32\x08.Address\"D\n\x13ReplicaListResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1f\n\rreplicaServer\x18\x02 \x01(\x0b\x32\x08.Address2\x80\x01\n\x16\x43ommWithRegistryServer\x12\x30\n\x08Register\x12\x08.Address\x1a\x18.RegisterReplicaResponse\"\x00\x12\x34\n\x0egetReplicaList\x12\x08.Address\x1a\x14.ReplicaListResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CommWithRegistryServer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDRESS._serialized_start=32
  _ADDRESS._serialized_end=67
  _REGISTERREPLICARESPONSE._serialized_start=69
  _REGISTERREPLICARESPONSE._serialized_end=150
  _REPLICALISTRESPONSE._serialized_start=152
  _REPLICALISTRESPONSE._serialized_end=220
  _COMMWITHREGISTRYSERVER._serialized_start=223
  _COMMWITHREGISTRYSERVER._serialized_end=351
# @@protoc_insertion_point(module_scope)
